# Generated by Django 3.0.8 on 2020-07-21 19:26

import colorfield.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AxisPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.PositiveIntegerField(default=0)),
                ('y_axis', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BaseSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), size=4)),
                ('type', models.CharField(max_length=20)),
                ('noGameColor', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='MapGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('col', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('row', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='Teleportal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_connection', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='MapSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.AxisPosition')),
                ('base_square', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.BaseSquare')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='mapa.MapGame')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_square', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapa.MapSquare')),
            ],
        ),
    ]
